name: first workflow 
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet the user
        run: echo welcome to Github Actions
      
  
    

